"use client";

import "../styles/global.css";
import Head from "next/head";

import Loading from "../components/Loading.js";

import { ThemeProvider } from "next-themes";
import { useEffect } from "react";
import Router, { useRouter } from "next/router";
import useAuthStore from "@/utils/store/auth/authStore";

function MyApp({ Component, pageProps }) {
  const { loading, setIsLoading } = useAuthStore();
  const router = useRouter();
  const getLayout = Component.getLayout || ((page) => page);

  useEffect(() => {
    const start = (url) => {
      if (router.pathname === "/auth/login" && url.includes("/dashboard/")) {
        setIsLoading(true);
      }
    };
    const end = () => setIsLoading(false);

    Router.events.on("routeChangeStart", start);
    Router.events.on("routeChangeComplete", end);
    Router.events.on("routeChangeError", end);

    return () => {
      Router.events.off("routeChangeStart", start);
      Router.events.off("routeChangeComplete", end);
      Router.events.off("routeChangeError", end);
    };
  }, [router.pathname]);

  return getLayout(
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icons/etech7_favicon.ico" />
      </Head>
      {loading ? (
        <Loading />
      ) : (
        <ThemeProvider attribute="class">
          <Component {...pageProps} />
        </ThemeProvider>
      )}
    </>
  );
}

export default MyApp;
