import "prismjs/themes/prism.css";
import "prismjs/components/prism-markup-templating.js";
import "prismjs/components/prism-c";
import "prismjs/components/prism-cpp";
import "prismjs/components/prism-objectivec";
import "prismjs/components/prism-python";
import "prismjs/components/prism-ruby";
import "prismjs/components/prism-java";
import "prismjs/components/prism-javascript";
import "prismjs/components/prism-php";
import "prismjs/components/prism-go";
import "prismjs/components/prism-typescript";
import "prismjs/components/prism-dart";
import "prismjs/components/prism-julia";
import "prismjs/components/prism-r";
import "prismjs/components/prism-matlab";
import "prismjs/components/prism-lua";
import "prismjs/components/prism-groovy";
import "prismjs/components/prism-scala";
import "prismjs/components/prism-fsharp";
import "prismjs/components/prism-clojure";
import "prismjs/components/prism-elixir";
import "prismjs/components/prism-haxe";
import "prismjs/components/prism-swift";
import "prismjs/components/prism-csharp"
import "prismjs/components/prism-fortran"
import "prismjs/components/prism-excel-formula"
import "prismjs/components/prism-json"
import "prismjs/components/prism-sql"
import "prismjs/components/prism-mongodb"
import "prismjs/components/prism-graphql"
import "prismjs/components/prism-fortran"
import "prismjs/components/prism-cobol"
import "prismjs/components/prism-jsx"
import "prismjs/components/prism-kotlin"
import "prismjs/components/prism-yaml"
import "prismjs/components/prism-regex"
import "prismjs/components/prism-bash"
