name: Build and deploy Node.js app to Azure Web App - myautopilot

on:
  push:
    branches:
      - beta
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - name: Print environment variables directly
        run: |
          echo "Printing environment variables before assigning to file:"
          echo "NEXT_PUBLIC_DB_SERVICE_URL=${{ secrets.NEXT_PUBLIC_DB_SERVICE_URL }}"
          echo "NEXT_PUBLIC_CONNECTWISE_SERVICE_URL=${{ secrets.NEXT_PUBLIC_CONNECTWISE_SERVICE_URL }}"
          echo "NEXT_PUBLIC_GPT_SERVICE_URL=${{ secrets.NEXT_PUBLIC_GPT_SERVICE_URL }}"
          echo "NEXT_PUBLIC_EMAILCONNECTOR_URL=${{ secrets.NEXT_PUBLIC_EMAILCONNECTOR_URL }}"

      - name: Create env file for debugging
        run: |
          echo "Creating env_variables.txt file with environment variables"
          echo "NEXT_PUBLIC_DB_SERVICE_URL=${{ secrets.NEXT_PUBLIC_DB_SERVICE_URL }}" > env_variables.txt
          echo "NEXT_PUBLIC_CONNECTWISE_SERVICE_URL=${{ secrets.NEXT_PUBLIC_CONNECTWISE_SERVICE_URL }}" >> env_variables.txt
          echo "NEXT_PUBLIC_GPT_SERVICE_URL=${{ secrets.NEXT_PUBLIC_GPT_SERVICE_URL }}" >> env_variables.txt
          echo "NEXT_PUBLIC_EMAILCONNECTOR_URL=${{ secrets.NEXT_PUBLIC_EMAILCONNECTOR_URL }}" >> env_variables.txt

          echo "Contents of env_variables.txt:"
          type env_variables.txt

      - name: Upload environment variables file for viewing
        uses: actions/upload-artifact@v3
        with:
          name: env-variables
          path: env_variables.txt

      - name: npm install, build, and test
        run: |
          npm install
          echo "Running build with NODE_ENV=production"
          set NODE_ENV=production && npm run build
          npm run test --if-present
        env:
          NEXT_PUBLIC_DB_SERVICE_URL: ${{ secrets.NEXT_PUBLIC_DB_SERVICE_URL }}
          NEXT_PUBLIC_CONNECTWISE_SERVICE_URL: ${{ secrets.NEXT_PUBLIC_CONNECTWISE_SERVICE_URL }}
          NEXT_PUBLIC_GPT_SERVICE_URL: ${{ secrets.NEXT_PUBLIC_GPT_SERVICE_URL }}
          NEXT_PUBLIC_EMAILCONNECTOR_URL: ${{ secrets.NEXT_PUBLIC_EMAILCONNECTOR_URL }}

      - name: Upload build artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: .

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: "aiautopilot"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CBFB971C81674F04ABDBDA70AB2C6D56 }}
          package: .

      - name: Verify environment variables in deployment
        run: |
          echo "NEXT_PUBLIC_DB_SERVICE_URL: $NEXT_PUBLIC_DB_SERVICE_URL"
          echo "NEXT_PUBLIC_CONNECTWISE_SERVICE_URL: $NEXT_PUBLIC_CONNECTWISE_SERVICE_URL"
          echo "NEXT_PUBLIC_GPT_SERVICE_URL: $NEXT_PUBLIC_GPT_SERVICE_URL"
          echo "NEXT_PUBLIC_EMAILCONNECTOR_URL: $NEXT_PUBLIC_EMAILCONNECTOR_URL"
        env:
          NEXT_PUBLIC_DB_SERVICE_URL: ${{ secrets.NEXT_PUBLIC_DB_SERVICE_URL }}
          NEXT_PUBLIC_CONNECTWISE_SERVICE_URL: ${{ secrets.NEXT_PUBLIC_CONNECTWISE_SERVICE_URL }}
          NEXT_PUBLIC_GPT_SERVICE_URL: ${{ secrets.NEXT_PUBLIC_GPT_SERVICE_URL }}
          NEXT_PUBLIC_EMAILCONNECTOR_URL: ${{ secrets.NEXT_PUBLIC_EMAILCONNECTOR_URL }}
a
