name: Build and deploy Node.js app to Azure Web App - myautopilot

on:
  push:
    branches:
      - beta
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - name: Check and create env_variables.txt
        run: |
          echo "NEXT_PUBLIC_DB_SERVICE_URL: $NEXT_PUBLIC_DB_SERVICE_URL" >> env_variables.txt
          echo "NEXT_PUBLIC_CONNECTWISE_SERVICE_URL: $NEXT_PUBLIC_CONNECTWISE_SERVICE_URL" >> env_variables.txt
          echo "NEXT_PUBLIC_GPT_SERVICE_URL: $NEXT_PUBLIC_GPT_SERVICE_URL" >> env_variables.txt
          echo "NEXT_PUBLIC_EMAILCONNECTOR_URL: $NEXT_PUBLIC_EMAILCONNECTOR_URL" >> env_variables.txt
          cat env_variables.txt # Output the content to see in the logs
        env:
          NEXT_PUBLIC_DB_SERVICE_URL: ${{ secrets.NEXT_PUBLIC_DB_SERVICE_URL }}
          NEXT_PUBLIC_CONNECTWISE_SERVICE_URL: ${{ secrets.NEXT_PUBLIC_CONNECTWISE_SERVICE_URL }}
          NEXT_PUBLIC_GPT_SERVICE_URL: ${{ secrets.NEXT_PUBLIC_GPT_SERVICE_URL }}
          NEXT_PUBLIC_EMAILCONNECTOR_URL: ${{ secrets.NEXT_PUBLIC_EMAILCONNECTOR_URL }}

      - name: Upload env_variables.txt artifact
        uses: actions/upload-artifact@v3
        with:
          name: env-variables
          path: env_variables.txt

      - name: npm install, build, and test
        run: |
          npm install
          NODE_ENV=production npm run build
          npm run test --if-present
        env:
          NEXT_PUBLIC_DB_SERVICE_URL: ${{ secrets.NEXT_PUBLIC_DB_SERVICE_URL }}
          NEXT_PUBLIC_CONNECTWISE_SERVICE_URL: ${{ secrets.NEXT_PUBLIC_CONNECTWISE_SERVICE_URL }}
          NEXT_PUBLIC_GPT_SERVICE_URL: ${{ secrets.NEXT_PUBLIC_GPT_SERVICE_URL }}
          NEXT_PUBLIC_EMAILCONNECTOR_URL: ${{ secrets.NEXT_PUBLIC_EMAILCONNECTOR_URL }}

      - name: Upload build artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: .
