# my-yaml-file.yml

name: Build and deploy Node.js app to Azure Web App - myautopilot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Archive code
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./node-app.zip .

      - name: Upload zipped artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: ./node-app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download zipped artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app
          path: ./node-app.zip

      - name: Unzip artifact
        run: unzip node-app.zip

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "myautopilot"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_855ED72A758F4FA8A57DDE2D9DAA18C4 }}
          package: .
